objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${PROJECT_NAME}-deployment
    namespace: ${PROJECT_NAME}
    labels:
      app: ${PROJECT_NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${PROJECT_NAME}
    template:
      metadata:
        labels:
          app: ${PROJECT_NAME}
      spec:
        containers:
        - name: ${PROJECT_NAME}
          image: ${CLUSTER_IP}:5000/${PROJECT_NAME}
          ports:
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: {{.application}}
    name: ${PROJECT_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: {{.application}}
      deploymentconfig: ${PROJECT_NAME}
  status:
    loadBalancer: {}
- apiVersion: tekton.dev/v1alpha1
  kind: TaskRun
  metadata:
    name: s2i-${PROJECT_NAME}-taskrun
  spec:
    taskRef:
      name: s2i
    inputs:
      params:
      - name: BUILDER_IMAGE
        value: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
      - name: TLSVERIFY
        value: "false"
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: url
            value: https://github.com/dummy_org/dummy_repo
    outputs:
      resources:
      - name: image
        resourceSpec:
          type: image
          params:
          - name: url
            value: registry.docker-registry:5000/${PROJECT_NAME}
apiVersion: v1
kind: Template