objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: my-app
  spec: {}
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{.serviceName}}-deployment
    namespace: {{.serviceName}}
    labels:
      app: {{.serviceName}}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{.serviceName}}
    template:
      metadata:
        labels:
          app: {{.serviceName}}
      spec:
        containers:
        - name: {{.serviceName}}
          image: ${CLUSTER_IP}:5000/{{.serviceName}}
          ports:
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: {{.application}}
    name: {{.serviceName}}
  spec:
    type: NodePort
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: {{.application}}
      deploymentconfig: {{.serviceName}}
  status:
    loadBalancer: {}
apiVersion: v1
kind: Template